-- Generated by `pikku db generate` from pikkuBetterAuth (Better Auth).
-- Re-run the command after changing that source.

create table "invitation" ("id" text not null primary key, "organization_id" text not null references "organization" ("id") on delete cascade, "email" text not null, "role" text, "status" text not null, "expires_at" date not null, "created_at" date not null, "inviter_id" text not null references "user" ("id") on delete cascade);

create index "invitation_organization_id_idx" on "invitation" ("organization_id");

create index "invitation_email_idx" on "invitation" ("email");

create table "member" ("id" text not null primary key, "organization_id" text not null references "organization" ("id") on delete cascade, "user_id" text not null references "user" ("id") on delete cascade, "role" text not null, "created_at" date not null);

create index "member_organization_id_idx" on "member" ("organization_id");

create index "member_user_id_idx" on "member" ("user_id");

create table "organization" ("id" text not null primary key, "name" text not null, "slug" text not null unique, "logo" text, "created_at" date not null, "metadata" text);

-- REVIEWED. `issuer` arrives with better-auth 1.7 and is unrelated to the
-- organisation plugin this migration was generated for — it rides along because
-- the whole better-auth schema is regenerated at once.
--
-- The generator wrote it NOT NULL with no default, which is correct for a fresh
-- database and fails outright on one with accounts in it. It is given a default
-- of '' so the statement is safe either way, then backfilled from provider_id,
-- which is what better-auth derives the issuer from for the credential and
-- social providers this app has.
--
-- Left as DEFAULT '' rather than dropped after backfill: SQLite cannot alter a
-- column's constraints without rebuilding the table, and rebuilding `account`
-- to remove a default nothing reads is a worse trade than leaving it.
ALTER TABLE account ADD COLUMN issuer TEXT NOT NULL DEFAULT '';

UPDATE account SET issuer = provider_id WHERE issuer = '';

ALTER TABLE session ADD COLUMN active_organization_id TEXT;
