-- Generated by `pikku db generate` from pikkuBetterAuth (Better Auth).
-- Re-run the command after changing that source.

create table "device_code" ("id" text not null primary key, "device_code" text not null, "user_code" text not null, "user_id" text, "expires_at" date not null, "status" text not null, "last_polled_at" date, "polling_interval" integer, "client_id" text, "scope" text);

create unique index "device_code_device_code_uidx" on "device_code" ("device_code");

create unique index "device_code_user_code_uidx" on "device_code" ("user_code");
