-- Generated by `pikku db generate` from pikkuBetterAuth (Better Auth).
-- Re-run the command after changing that source.

create table "apikey" ("id" text not null primary key, "config_id" text not null, "name" text, "start" text, "reference_id" text not null, "prefix" text, "key" text not null, "refill_interval" integer, "refill_amount" integer, "last_refill_at" date, "enabled" integer, "rate_limit_enabled" integer, "rate_limit_time_window" integer, "rate_limit_max" integer, "request_count" integer, "remaining" integer, "last_request" date, "expires_at" date, "created_at" date not null, "updated_at" date not null, "permissions" text, "metadata" text);

create index "apikey_config_id_idx" on "apikey" ("config_id");

create index "apikey_reference_id_idx" on "apikey" ("reference_id");

create index "apikey_key_idx" on "apikey" ("key");
